[package]
name = "cimpl-stream"
version = "0.1.0"
edition = "2021"
authors = ["Adobe"]
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
cimpl = { path = ".." }

[build-dependencies]
cbindgen = "0.27"
